### ISSUE TITLE
Binaries for the 1.1 release seem to be missing

### ISSUE THREAD

**Issue by nadiaholmquist** [GPUCode/android_device_nokia_nb1#2]

**Comment by raphaelthegreat** [comment]
Sorry about that, I am working on redoing the installation though TWRP and I am facing some issues currently and when the images will be ready I will upload them. The problem is that I cannot delete a release so that is why it remains there

**Comment by nadiaholmquist** [comment]
Ah alright, no rush, I just wanted to point it out in case it was an oversight :)

**Comment by nadiaholmquist** [comment]
Don't have an xda account so I guess I'll just ask here even though I probably shouldn't... Is there any chance SELinux can ever work with this? I'm going to have to revert to stock because I need to pass ctsProfile for some stupid public sector apps to work...

**Comment by raphaelthegreat** [comment]
Setting selinux to enforcing is definitely in the roadmap. I am planning that for the third release :)

**Comment by radu-v** [comment]
SELinux is enforcing now, by the way

**Comment by nadiaholmquist** [comment]
Yeah tried out the latest crDroid build, though it seems like the issue I had still persists, the NemID app just crashes immediately on start.

**Comment by raphaelthegreat** [comment]
Have you tried using Magisk, to pass CTS? Maybe the app checks for SafetyNet too

**Comment by nadiaholmquist** [comment]
I found out that it's actually not about passing CTS after all, both my Nexus 5 and OnePlus 6T running Lineage but not passing are still able to run that app - I guess the issue must be somewhere else.

**Comment by raphaelthegreat** [comment]
If you are running crDroid, can you send a log? Just connect the phone to a PC, run adb logcat > run.log and launch the app. I cannot guarantee that I can fix it, but I can try

**Comment by nadiaholmquist** [comment]
```
--------- beginning of crash
01-04 17:44:20.610  3941 15491 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #4
01-04 17:44:20.610  3941 15491 E AndroidRuntime: Process: com.android.systemui, PID: 3941
01-04 17:44:20.610  3941 15491 E AndroidRuntime: java.lang.RuntimeException: Can't create handler inside thread Thread[AsyncTask #4,5,main] that has not called Looper.prepare()
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:227)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at android.os.Handler.<init>(Handler.java:129)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.assist.AssistManager.<init>(AssistManager.java:208)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.assist.AssistManager_Factory.provideInstance(AssistManager_Factory.java:107)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.assist.AssistManager_Factory.get(AssistManager_Factory.java:70)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.assist.AssistManager_Factory.get(AssistManager_Factory.java:17)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.lambda$startActivityDismissingKeyguard$16(StatusBar.java:2912)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.StatusBar.lambda$startActivityDismissingKeyguard$16$StatusBar(Unknown Source:0)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at com.android.systemui.statusbar.phone.-$$Lambda$StatusBar$fPMIOsYMhFXVKHESAjUObpcgeJM.run(Unknown Source:10)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
01-04 17:44:20.610  3941 15491 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:923)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: FATAL EXCEPTION: BackgroundHandlerThread
01-04 18:57:58.793 24454 24500 E AndroidRuntime: Process: dk.e_nettet.mobilekey.everyone, PID: 24454
01-04 18:57:58.793 24454 24500 E AndroidRuntime: java.security.ProviderException: Failed to load generated key pair from keystore
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:531)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:473)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at dk.danid.nemidmobilekey.assert.abstract(Unknown Source:149)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at dk.danid.nemidmobilekey.switch$1$1.run(Unknown Source:332)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:263)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:303)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:315)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:522)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	... 8 more
01-04 18:57:58.793 24454 24500 E AndroidRuntime: Caused by: android.security.KeyStoreException: Invalid key blob
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:265)
01-04 18:57:58.793 24454 24500 E AndroidRuntime: 	... 11 more
01-04 18:57:59.378 24526 24567 E AndroidRuntime: FATAL EXCEPTION: BackgroundHandlerThread
01-04 18:57:59.378 24526 24567 E AndroidRuntime: Process: dk.e_nettet.mobilekey.everyone, PID: 24526
01-04 18:57:59.378 24526 24567 E AndroidRuntime: java.security.ProviderException: Failed to load generated key pair from keystore
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:531)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.generateKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:473)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at java.security.KeyPairGenerator$Delegate.generateKeyPair(KeyPairGenerator.java:727)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at dk.danid.nemidmobilekey.assert.abstract(Unknown Source:149)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at dk.danid.nemidmobilekey.switch$1$1.run(Unknown Source:332)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:223)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: Caused by: java.security.UnrecoverableKeyException: Failed to obtain X.509 form of public key
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:263)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:303)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStoreKeyPairFromKeystore(AndroidKeyStoreProvider.java:315)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreKeyPairGeneratorSpi.loadKeystoreKeyPair(AndroidKeyStoreKeyPairGeneratorSpi.java:522)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	... 8 more
01-04 18:57:59.378 24526 24567 E AndroidRuntime: Caused by: android.security.KeyStoreException: Invalid key blob
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:1301)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	at android.security.keystore.AndroidKeyStoreProvider.loadAndroidKeyStorePublicKeyFromKeystore(AndroidKeyStoreProvider.java:265)
01-04 18:57:59.378 24526 24567 E AndroidRuntime: 	... 11 more
```

**Comment by raphaelthegreat** [comment]
Could you upload a complete log? Most often the the underlaying issue appears before the crash

**Comment by radu-v** [comment]
Which Android version are you running on your other phones, where the app runs fine?
Is the app compatible with Android 11? I tried it on my Oneplus 6t, running PiXeN OS 11 and it just shows "Device is not supported, The NemID code app can not run on your device for security purposes (4042)"

**Comment by nadiaholmquist** [comment]
http://nhp.sh/f/nemid.log

On my 6T I'm running LineageOS 18.1, if you have magisk installed you must use magisk hide on the app or it will show that message. On the Nokia 8 it crashes immediately before even having the chance to show it, though.
